name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }} # Add this secret to your repo
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Build with Maven
      run: ./mvnw package spring-boot:build-image
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push image
      run: |
        docker tag ghcr.io/collinsrj/demodeployment:0.0.1-SNAPSHOT ghcr.io/collinsrj/demodeployment:${{ github.sha }}
        docker push ghcr.io/collinsrj/demodeployment:0.0.1-SNAPSHOT
        docker push ghcr.io/collinsrj/demodeployment:${{ github.sha }}
      
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./azuredeploy.bicep
        parameters: containerImage=ghcr.io/collinsrj/demodeployment:${{ github.sha }}
 